name: aoc
description: A package providing reusable code for solving AoC challenges.
version: 1.0.0
repository: https://github.com/JeroenWeener/advent_of_code
publish_to: none

environment:
  sdk: '>=2.19.3 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
